Añadir mi idea de base de datos
Gianibruno/Trabajo-Final-Laboratorio-Programacion-I pull request #3
Opened 2021-05-24 18:59 UTC by AstorArico72

Aquí está mi idea de base de datos SQL.
He puesto valores de límite como 127 por basarme en la potencia de 2.
Se agradece cualquier corrección.

2021-05-24 19:43 UTC, Gianibruno requested changes
No eliminar.

2021-05-25 18:46 UTC, AstorArico72 commented
> No eliminar.

¿Cómo? Ya borré los archivos de mi rama porque creí que se duplicarían.

2021-05-25 22:08 UTC, PabloBarrionuevo commented
> > No eliminar.
> 
> ¿Cómo? Ya borré los archivos de mi rama porque creí que se duplicarían.

Actualiza tu rama para que quede como el main en el rep de Gian (Ver issues), después agrega tu SQL a tu copia del rep, y después haces pull requests para Gian.

2021-05-25 22:09 UTC, PabloBarrionuevo commented
Igualmente revisa tu sql, para que cumpla con la consigna. La biblioteca contiene ejemplares de libros, tenes que hacer una tabla de ejemplares, que cada ejemplar sea de algún libro, y que estos ejemplares sean los que se prestan a los lectores.

2021-05-26 02:58 UTC, AstorArico72 commented
Creo que no puedo recuperar los archivos. Voy a borrar mi rama y rehacerla.

2021-05-26 02:58 UTC, closed without merging